#!/usr/bin/env python3
"""Materialize native Hazard3 equivalents of the integer Arm benchmarks."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ALU_OPS = {
    "nop16", "add16", "add32", "lsl_reg", "mul", "umull",
    "sdiv_fast", "sdiv_mid", "sdiv_slow",
    "udiv_fast", "udiv_mid", "udiv_slow",
}


def kernel_body(op: str) -> tuple[list[str], list[str]]:
    setup: list[str] = []
    unit: list[str]
    if op == "nop16":
        unit = ["c.nop"]
    elif op == "add16":
        setup = ["li a0, 1"]
        unit = ["c.addi a0, 1"]
    elif op == "add32":
        setup = ["li a0, 1", "li a1, 1"]
        unit = ["add a0, a0, a1"]
    elif op == "lsl_reg":
        setup = ["li a0, 0xff", "li a1, 4"]
        unit = ["sll t0, a0, a1"]
    elif op == "mul":
        setup = ["li a0, 0x1234", "li a1, 0x5678"]
        unit = ["mul t0, a0, a1"]
    elif op == "umull":
        # RV32 has separate low/high multiply instructions. One logical
        # 32x32->64 operation is therefore this two-instruction pair.
        setup = ["li a0, 0x1234"]
        unit = ["mul t0, a0, a0", "mulhu t1, a0, a0"]
    elif op.startswith(("sdiv_", "udiv_")):
        signed = op.startswith("sdiv_")
        case = op.rsplit("_", 1)[1]
        operands = {
            "fast": (1, -2 if signed else 0xFFFFFFFE),
            "mid": (0x00FFFFFF, 0x10),
            "slow": (0x7FFFFFFF if signed else 0xFFFFFFFF, 1),
        }[case]
        setup = [f"li a0, {operands[0]}", f"li a1, {operands[1]}"]
        unit = [("div" if signed else "divu") + " t0, a0, a1"]
    else:
        raise ValueError(f"unsupported integer operation: {op}")
    return setup, unit


def generate(bench: str) -> str:
    match = re.fullmatch(
        r"bench_(.+)_(8|9|16|24|32|40|48|56|64|72|80|100)", bench
    )
    if not match:
        raise ValueError(f"unrecognized benchmark name: {bench}")
    op, count_text = match.groups()
    if op not in ALU_OPS:
        raise ValueError(
            f"{bench} is not an integer benchmark; RP2350 Hazard3 has no FPU"
        )
    count = int(count_text)
    setup, unit = kernel_body(op)

    def emit(lines: list[str]) -> str:
        return "\n".join(f"    {line}" for line in lines)

    if op == "add32":
        repeated = (
            "    .option push\n"
            "    .option norvc\n"
            f"    .rept {count}\n{emit(['add a0, a0, a1'])}\n    .endr\n"
            "    .option pop"
        )
    else:
        repeated = f"    .rept {count}\n{emit(unit)}\n    .endr"

    return f"""/*
 * {bench} — Hazard3/RV32 native equivalent of the Arm integer kernel.
 * Generated by rp2350/riscv/generate_kernel.py; edit the generator or shared
 * RISC-V harness rather than hand-editing this file.
 */
#include "riscv/harness.h"

    RISCV_BENCH
{emit(setup)}
{repeated}
    RISCV_END_BENCH
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bench")
    parser.add_argument("--output", type=Path)
    parser.add_argument(
        "--all-from", type=Path,
        help="Directory containing the canonical Arm bench_*.S files",
    )
    parser.add_argument(
        "--output-dir", type=Path,
        help="Destination directory used with --all-from",
    )
    args = parser.parse_args()
    if args.all_from or args.output_dir:
        if not args.all_from or not args.output_dir or args.bench or args.output:
            parser.error("use --all-from and --output-dir together by themselves")
        sources = sorted(args.all_from.glob("bench_*.S"))
        if len(sources) != 56:
            parser.error(f"expected 56 Arm integer kernels, found {len(sources)}")
        args.output_dir.mkdir(parents=True, exist_ok=True)
        for source in sources:
            (args.output_dir / source.name).write_text(generate(source.stem))
        print(f"generated {len(sources)} Hazard3 kernels in {args.output_dir}")
    else:
        if not args.bench or not args.output:
            parser.error("use --bench and --output, or --all-from and --output-dir")
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(generate(args.bench))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
