#!/usr/bin/env python3
"""Materialize the Hazard3 equivalents of the Arm control-flow kernels."""

from pathlib import Path


HERE = Path(__file__).resolve().parent
COUNTS = (8, 9, 16, 100)
FAMILIES = (
    "baseline_nop16", "direct_forward16", "direct_forward32",
    "conditional_taken", "conditional_not_taken", "loop_body1",
    "loop_body4", "call_direct", "call_indirect", "jump_indirect",
    "target_aligned", "target_halfword", "cbz_taken", "cmpbeq_taken",
)


def body(family: str, count: int) -> str:
    repeat = f"    .rept {count}\n"
    end = "    .endr\n"
    if family == "baseline_nop16":
        return repeat + "    c.nop\n" + end
    if family == "direct_forward16":
        return repeat + "    c.j 1f\n    c.nop\n1:  c.nop\n" + end
    if family == "direct_forward32":
        return (repeat + "    .option push\n    .option norvc\n"
                "    jal zero, 1f\n    .option pop\n    c.nop\n1:  c.nop\n" + end)
    if family == "conditional_taken":
        return "    li t0, 0\n" + repeat + "    beq t0, zero, 1f\n    c.nop\n1:  c.nop\n" + end
    if family == "conditional_not_taken":
        return "    li t0, 1\n" + repeat + "    beq t0, zero, 1f\n    c.nop\n1:  c.nop\n" + end
    if family in ("loop_body1", "loop_body4"):
        nops = 1 if family == "loop_body1" else 4
        return (f"    li t0, {count}\n1:\n" + "    c.nop\n" * nops
                + "    addi t0, t0, -1\n    bne t0, zero, 1b\n")
    if family == "call_direct":
        return ("    addi sp, sp, -16\n    sw ra, 12(sp)\n" + repeat
                + "    .option push\n    .option norvc\n    jal ra, 2f\n"
                  "    .option pop\n" + end
                + "    lw ra, 12(sp)\n    addi sp, sp, 16\n    ret\n"
                  "2:  c.nop\n    ret\n")
    if family == "call_indirect":
        return ("    addi sp, sp, -16\n    sw ra, 12(sp)\n    lla t0, 2f\n"
                + repeat + "    .option push\n    .option norvc\n"
                  "    jalr ra, 0(t0)\n    .option pop\n" + end
                + "    lw ra, 12(sp)\n    addi sp, sp, 16\n    ret\n"
                  "2:  c.nop\n    ret\n")
    if family == "jump_indirect":
        return (repeat + "    lla t0, 1f\n    .option push\n"
                "    .option norvc\n    jalr zero, 0(t0)\n"
                "    .option pop\n    c.nop\n1:  c.nop\n" + end)
    if family == "target_aligned":
        return repeat + "    c.j 1f\n    c.nop\n    .balign 4\n1:  c.nop\n" + end
    if family == "target_halfword":
        return repeat + "    c.j 1f\n    c.nop\n    .balign 4\n    c.nop\n1:  c.nop\n" + end
    if family == "cbz_taken":
        return "    li a0, 0\n" + repeat + "    c.beqz a0, 1f\n    c.nop\n1:  c.nop\n" + end
    if family == "cmpbeq_taken":
        # RV32 has no condition flags or a separate CMP instruction.
        # SLTIU creates the zero-test result, then BNE consumes it.
        return ("    li t0, 0\n" + repeat
                + "    sltiu t1, t0, 1\n    bne t1, zero, 1f\n"
                  "    c.nop\n1:  c.nop\n" + end)
    raise ValueError(family)


def main() -> None:
    for family in FAMILIES:
        for count in COUNTS:
            name = f"bench_cf_{family}_{count}"
            source = (
                f"/* {name}: {count} control-flow events on RP2350 Hazard3.\n"
                " * Timed code executes from non-striped SRAM8/Scratch X.\n"
                " * Generated by generate.py; edit that file to change the set.\n"
                " */\n"
                '#include "riscv/harness.h"\n\n'
                "    RISCV_BENCH\n"
                + body(family, count)
                + "    RISCV_END_BENCH\n"
            )
            path = HERE / f"{name}.S"
            if not path.exists() or path.read_text() != source:
                path.write_text(source)
    print(f"Generated {len(FAMILIES) * len(COUNTS)} Hazard3 control-flow kernels")


if __name__ == "__main__":
    main()
